#!/bin/bash

let recursive=0
let force=0
while getopts "rf" opt; do
    case $opt in
        f) :
            force=1
            ;;
        r) :
            recursive=1
            ;;
        \?) :
            echo "invalid argument"
            exit 255
    esac
done

TRASH=$HOME/.trash

if [[ ! -d $TRASH ]];
then
    mkdir $TRASH
fi

shift $(($OPTIND - 1))
for f in $*;
do
    if [[ ! -e $f ]];
    then
        if [[ $force -eq 1 ]];
        then
            continue
        else
            echo "$0: no such file or directory '$f'"
            exit 1
        fi
    fi

    if [[ -d $f && $recursive -eq 0 ]];
    then
        if [[ $force -eq 1 ]];
        then
            exit 0
        else
            echo "$0: $f is a directory"
            exit 1
        fi
    fi

    name=$(basename $f)

    if [[ -z $name ]];
    then
        continue
    fi

    if [[ -e $TRASH/$name ]];
    then
        ts=$(date +%s)
        mv -f $TRASH/$name $TRASH/${name}_${ts}
    fi

    # sometimes $TRASH/$name still exist
    /bin/rm -rf $TRASH/$name

    mv -f $f $TRASH/
done

# rm files which last change time older than 10days ago
# exclude $TRASH self
for f in `find $TRASH -maxdepth 1 -ctime +2`;
do
    if [[ "$f" == "$TRASH" ]];
    then
        continue
    fi

    /bin/rm -rf $f
done

exit 0
